### ISSUE TITLE
Conversion issue

### ISSUE THREAD

**Issue by dkonigsfeld** [Republic-at-War/Republic-At-War#1]
Is anyone else having a problem with loading in the 1.2 version? I have the 1.1.5 version up and running through steam properties but I can't seem to properly launch the 1.2 version. If anyone knows how to get it to run through steam let me know.

**Comment by Starscream22** [comment]
i thought RAW 1.2was not even released yet

**Comment by Starscream22** [comment]
https://www.youtube.com/watch?v=xcsMRay_L6M

this should help

**Comment by dkonigsfeld** [comment]
I thought thats what the files on here were?

**Comment by Starscream22** [comment]
go in to your raw 1.2 folder tell me what files are there i downloaded it and its not complete

**Comment by Starscream22** [comment]
as far as i know RAW 1.2 is still in development can you send me the list of folders that are in the down load they should contain art text xmls

**Comment by Rextoronon** [comment]
Starscream22 is right. v1.2 is not released. Its still in development. You can go see updates on moddb about it.

**Comment by AnakinRaW** [comment]
This repository will not contain the full mod. it can be seen as a online reference to existing code. This will allow us to discuss better about existing bugs.

**Comment by anderson2927** [comment]
When will this contain the full mod?

**Comment by AnakinRaW** [comment]
sorry my fault. i forgot to write the most important word in this sentence, which was "not". 

so again this repo will NOT contain the full mod. github just is not made for this

**Comment by KSANDS1310** [comment]
what files do I need to download to get the most updated version of the mod? Is it the files in the version folder? they say copy of 1.1.5 so I'm a bit confused

**Comment by Starscream22** [comment]
here you go this is the link 

http://www.moddb.com/mods/republic-at-war/downloads/republic-at-war-v115-auto-installer
remember to make a back up of your data folder

**Comment by Starscream22** [comment]
this is how to install it 

https://www.youtube.com/watch?v=xYCCktHOZIE

**Comment by Starscream22** [comment]
other instruction on how to install 

https://www.youtube.com/watch?v=b1uuaabIuTM
