### ISSUE TITLE
Units Frozen

### ISSUE THREAD

**Issue by tabsnotspaces9** [Republic-at-War/Republic-At-War#2]
I've run into the Forces of Corruption bug where units become unselectable. There's another mod that fixes base FoC saves (http://www.moddb.com/mods/thrawns-revenge/downloads/unit-selection-freeze-fixer-utility-v2), but it does not look like the XML changes are compatible with Republic at War.

**Comment by Rextoronon** [comment]
well i do get this problem sometimes. What i do is go to the menu button and come back. It works again.
However, it would be a nice thing to fix it.

**Comment by Starscream22** [comment]
try downloading the defreezer as alex says that will solve it and yes it is compatible with RAW
