### ISSUE TITLE
Units unselectable and capital ships losing sub systems

### ISSUE THREAD

**Issue by Basor011** [Republic-at-War/Republic-At-War#3]
This happened to me twice now,once as the CIS the other time as the Republic,basically when a i capture or lose Geonosis in a space battle,all ships lose their sub systems so they are like a corvette and are unselectable (not even ctrl a works)
I hope that you can help me 
Thanks (I am also not sure if the loss/win over geonosis space battle causes this)

**Comment by Starscream22** [comment]
for the units being unselectable  try this its the defreezer  
http://www.moddb.com/mods/thrawns-revenge/downloads/unit-selection-freeze-fixer-utility-v2

also how to use it see this 


https://www.youtube.com/watch?v=RTPt6LOdbVw
