### ISSUE TITLE
How to install the new launcher that was posted here?

### ISSUE THREAD

**Issue by Basor011** [Republic-at-War/Republic-At-War#4]
I can't find a tutorial anywhere,it doesn't have any instructions and doesn't have anything to run it,
Any help would be appreciated 
Thanks

**Comment by Starscream22** [comment]
As far as know the new version of Raw is not released yet   if you are looking for the mod you can get it from here it is version 1.15 

http://www.moddb.com/mods/republic-at-war/downloads/republic-at-war-v115-auto-installer
