### ISSUE TITLE
Christophsis Skirmish Glitch (Spawning with nothing but a shield generator)

### ISSUE THREAD

**Issue by TheProtato923** [Republic-at-War/Republic-At-War#5]
When I try skirmish on the Christophsis custom map (Which I have to press the custom maps button for) all there is a shield generator? What am I doing wrong? Aside from random crashes during the galactic conquest the game seems to run fine? I created an account btw this is not spam.

I am not using a pirated copy of the game as I purchased the game on Steam.

I would appreciate help around now as I'm honestly losing my patience for strange random problems like this.

Btw I also left this message on the mod db. I'm trying my best to get the word out asap so I can fix this problem as fast as possible.

**Comment by AnakinRaW** [comment]
fixed in 1.2
